# Boolean Arrays

In [25]:
import numpy as np # importing a function to create data arrays -- y'all won't need to do this part

# creating some fake data -- y'all won't have to do this part
cat_colors = np.array(['brown', 'black', 'black', 'grey', 'white', 'orange', 'black'])
cat_names = np.array(['nemo', 'lady', 'simba', 'tramp', 'snow', 'kitty', 'star'])

In [27]:
# let's say i want the names of all the black cats

# first method, is loops and if statements. this is the long way we want to avoid
black_cats = [] # create an empty list that will contain the names of black cats
for i in range(len(cat_colors)): # setting up a loop to go through all the cat colors
    if cat_colors[i] == 'black': # our conditional to get black cats
        black_cats.append(cat_names[i]) # if the conditional is true, add the corresponding name

In [29]:
black_cats # checking that it worked correctly

['lady', 'simba', 'star']

## Boolean

The above is too long! Let's use an easier way.

Boolean is a data type. The value can be True (1) or False (0).

In [34]:
# create a boolean array
# we first need to give it a name
# then you have 1 equal sign to assign it the value of the Boolean array
# on the right of the equal sign, you have the condition
# boolean_array = condition
black_color = cat_colors == 'black' 
# black_color is the name of the Boolean array
# cat_colors == 'black' is the condition

In [36]:
# check the Boolean array -- it will be full of True and False
black_color # it will be the same length as cat_colors

array([False,  True,  True, False, False, False,  True])

In [49]:
# use boolean array to pull out other data that corresponds to True
# to do this, you say the name of the array you want to pull from then [Boolean array]
cat_names[black_color]

array(['lady', 'simba', 'star'], dtype='<U5')

In [ ]:
# we can also save the data to a new variable
black_cats_bol = cat_names[black_color] # original data[boolean array]

In [51]:
# check the array of names of black cats
black_cats_bol

array(['lady', 'simba', 'star'], dtype='<U5')

In [44]:
# another example
food = np.array(['pizza', 'pizza', 'orange', 'chips', 'grape', 'cheese'])
cost = np.array([2, 3, 5, 6, 1, 4])

# pull out the cost of all the pizza
pizzas = food == 'pizza' # create the boolean array
pizza_cost = cost[pizzas] # pull out the corresponding data from the cost array
pizza_cost

array([2, 3])

In [46]:
# one more example
price = np.array([23, 45, 100, 34, 12])
weight = np.array([13, 14, 15, 16, 17])

# i want the price of everything that weighs more than 15
heavy = weight > 15 # create a boolean array
price_heavy = price[heavy] # pull out the prices of everything that fits the weight category
price_heavy

array([34, 12])