In [2]:
import numpy as np
my_array = np.array([1, 2, 5, 7])
print(my_array)

[1 2 5 7]


In [5]:
array2 = np.linspace(0,10,5) # if you know number of points
print(array2)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.mean(arr))
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.max(arr) + np.min(arr))
print(np.mean(arr) + np.sum(arr) + np.min(arr) + np.max(arr))

3.5
21
1
6
7
31.5


In [13]:
def sum_and_average(array1, array2):
    summed_array = array1 + array2
    return np.mean(summed_array)

array1 = np.random.randint((4))
print(array1)


array2 = np.random.randint((4))
print(array2)

mean_array = sum_and_average(array1, array2)
print(mean_array)

2
2
4.0


In [9]:
my_array = np.array([5, 10, 15, 20, 25])
print(my_array)
my_array = np.linspace(5,25,5)
my_array = my_array * 3
print(my_array)

[ 5 10 15 20 25]
[15. 30. 45. 60. 75.]


In [11]:
def sum_and_average(array1, array2):
    summed_array = array1 + array2
    return np.mean(summed_array)

array1 = np.random.randint((6))
print(array1)
array2 = np.random.randint((6))
print(array2)

mean_array = sum_and_average(array1, array2)
print(mean_array)


4
5
9.0


In [16]:
# import numpy
import numpy as np

#print random numbers between 0-20
print(np.random.randint(-5,20))



random_num = np.random.randint(-5,20)
print(random_num)





13
-4


In [24]:
options = [0, 5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80]
print(np.random.choice(options))
random_num = np.random.choice(options)
print(random_num)


80
50


In [ ]:
user_number = int(input("Enter a number: "))
print(type(user_number))

In [17]:
# Define Lunch Options
import numpy as np
lunch_options = ["Pizza", "Cheeseburger", "Chicken Fingers", "Salad", "Quesadilla"]
print(lunch_options)
print(np.random.choice(lunch_options))

def what_should_i_eat():
    """Function to suggest a random lunch option from a predefined list."""

    # Define a list of lunch options
    lunch_options = ["Pizza", "Sushi", "Tacos", "Salad", "Burger", "Sandwich"]

    # Choose a random lunch option
    random_lunch = np.random.choice(lunch_options)

    # Print the choice
    print(f"You should eat {random_lunch} for lunch today!")

['Pizza', 'Cheeseburger', 'Chicken Fingers', 'Salad', 'Quesadilla']
Cheeseburger


In [16]:
def what_should_i_eat():
    """Function to suggest a random lunch option from a predefined list."""

    # Define a list of lunch options
    lunch_options = ["Pizza", "Sushi", "Tacos", "Salad", "Burger", "Sandwich"]

    # Choose a random lunch option
    random_lunch = np.random.choice(lunch_options)

    # Print the choice
    print(f"You should eat {random_lunch} for lunch today!")

In [18]:
def what_should_i_eat_vegeterian(vegeterian = False):
    """Function to suggest a random lunch option from a predefined list.
    
    input:
    vegeterian: bool, if True, suggests only vegetarian options
    """
    if vegeterian:
        lunch_options = ["Cheese pizza", "Salad", "Veggie tacos", "Salad", "Veggie sandwich"]
    else:
        lunch_options = ["Pepperoni pizza", "Burger", "Sushi", "Meat tacos", "Salad", "Meat sandwich"]

    # Choose a random lunch option
    random_lunch = np.random.choice(lunch_options)

    # Print the choice
    print(f"You should eat {random_lunch} for lunch today! It's {'vegetarian' if vegeterian else 'not vegetarian'}.")

In [30]:
def magic_eightball():
    question = input(" What is your question for the magic 8 ball?")

    possible_answers = input(" Yes ", " No ", " Maybe ", " Hell No ", "Fuck You ")

    random_answer = np.random_choice(possible_answers)
    
    print(question)
    print(f"The Magic 8 Ball Says: {random_answer}") 

num1 = np.random.randint(1, 10)
num2 = np.random.randint(1, 10)


correct_answer = num1 + num2

user_answer = int(input(f"What is {num1} + {num2}?"))
 # Check if the user's answer is correct
        user_correct = user_answer == correct_answer

        if user_correct:
            print("Correct! Well done.")
        else:
            print(f"Incorrect. Guess again.")

i = 0
while i < 10:
    print(i)
    i += 1
print("Loop Finished")


IndentationError: unexpected indent (248219237.py, line 19)

In [29]:
def math_quiz_loop():
    """Function to ask a simple math question and check the answer."""
    
    # Generate two random numbers
    num1 = np.random.randint(1, 10)
    num2 = np.random.randint(1, 10)
    
    # Calculate the correct answer
    correct_answer = num1 + num2

    # Initialize our termination condition
    user_correct = False

    while not user_correct:
        # Ask the user for their answer
        user_answer = int(input(f"What is {num1} + {num2}? "))
    
        # Check if the user's answer is correct
        user_correct = user_answer == correct_answer

        if user_correct:
            print("Correct! Well done.")
        else:
            print(f"Incorrect. Guess again.")
